# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(608, 573)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.determenstic_queue = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.determenstic_queue.sizePolicy().hasHeightForWidth())
        self.determenstic_queue.setSizePolicy(sizePolicy)
        self.determenstic_queue.setMinimumSize(QtCore.QSize(0, 501))
        self.determenstic_queue.setMaximumSize(QtCore.QSize(16777215, 501))
        self.determenstic_queue.setObjectName("determenstic_queue")
        self.widget = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setContentsMargins(10, -1, -1, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.gridLayout_3.addWidget(self.comboBox, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 0, 1, 1)
        self.initial_no_of_customers = QtWidgets.QLabel(self.widget)
        self.initial_no_of_customers.setObjectName("initial_no_of_customers")
        self.gridLayout.addWidget(self.initial_no_of_customers, 3, 0, 1, 1)
        self.service_rate = QtWidgets.QLabel(self.widget)
        self.service_rate.setObjectName("service_rate")
        self.gridLayout.addWidget(self.service_rate, 1, 0, 1, 1)
        self.arrival_rate = QtWidgets.QLabel(self.widget)
        self.arrival_rate.setObjectName("arrival_rate")
        self.gridLayout.addWidget(self.arrival_rate, 0, 0, 1, 1)
        self.la = QtWidgets.QLabel(self.widget)
        self.la.setObjectName("la")
        self.gridLayout.addWidget(self.la, 2, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cancel = QtWidgets.QPushButton(self.widget)
        self.cancel.setObjectName("cancel")
        self.horizontalLayout_4.addWidget(self.cancel)
        self.compute_deterministic = QtWidgets.QPushButton(self.widget)
        self.compute_deterministic.setObjectName("compute_deterministic")
        self.horizontalLayout_4.addWidget(self.compute_deterministic)
        self.make_graph = QtWidgets.QPushButton(self.widget)
        self.make_graph.setObjectName("make_graph")
        self.horizontalLayout_4.addWidget(self.make_graph)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 2, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.input_service_rate = QtWidgets.QLineEdit(self.widget)
        self.input_service_rate.setObjectName("input_service_rate")
        self.gridLayout_2.addWidget(self.input_service_rate, 1, 0, 1, 1)
        self.input_capcity = QtWidgets.QLineEdit(self.widget)
        self.input_capcity.setObjectName("input_capcity")
        self.gridLayout_2.addWidget(self.input_capcity, 2, 0, 1, 1)
        self.input_limit = QtWidgets.QLineEdit(self.widget)
        self.input_limit.setObjectName("input_limit")
        self.gridLayout_2.addWidget(self.input_limit, 4, 0, 1, 1)
        self.input_intial_no_of_customers = QtWidgets.QLineEdit(self.widget)
        self.input_intial_no_of_customers.setObjectName("input_intial_no_of_customers")
        self.gridLayout_2.addWidget(self.input_intial_no_of_customers, 3, 0, 1, 1)
        self.input_arrival_rate = QtWidgets.QLineEdit(self.widget)
        self.input_arrival_rate.setObjectName("input_arrival_rate")
        self.gridLayout_2.addWidget(self.input_arrival_rate, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_16 = QtWidgets.QLabel(self.widget)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_3.addWidget(self.label_16)
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_3.addWidget(self.label_14)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.no_of_customers = QtWidgets.QLabel(self.widget)
        self.no_of_customers.setObjectName("no_of_customers")
        self.verticalLayout_5.addWidget(self.no_of_customers)
        self.waiting_time = QtWidgets.QLabel(self.widget)
        self.waiting_time.setObjectName("waiting_time")
        self.verticalLayout_5.addWidget(self.waiting_time)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        self.comboBox.raise_()
        self.determenstic_queue.addTab(self.widget, "")
        self.widget_2 = QtWidgets.QWidget()
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.av_no_of_customers_in_q = QtWidgets.QLabel(self.widget_2)
        self.av_no_of_customers_in_q.setObjectName("av_no_of_customers_in_q")
        self.verticalLayout_4.addWidget(self.av_no_of_customers_in_q)
        self.av_no_of_customers_in_system = QtWidgets.QLabel(self.widget_2)
        self.av_no_of_customers_in_system.setObjectName("av_no_of_customers_in_system")
        self.verticalLayout_4.addWidget(self.av_no_of_customers_in_system)
        self.av_waiting_time_in_q = QtWidgets.QLabel(self.widget_2)
        self.av_waiting_time_in_q.setObjectName("av_waiting_time_in_q")
        self.verticalLayout_4.addWidget(self.av_waiting_time_in_q)
        self.av_waiting_time_in_system = QtWidgets.QLabel(self.widget_2)
        self.av_waiting_time_in_system.setObjectName("av_waiting_time_in_system")
        self.verticalLayout_4.addWidget(self.av_waiting_time_in_system)
        self.horizontalLayout_25.addLayout(self.verticalLayout_4)
        self.cancel_sto = QtWidgets.QPushButton(self.widget_2)
        self.cancel_sto.setObjectName("cancel_sto")
        self.horizontalLayout_25.addWidget(self.cancel_sto)
        self.compute_stochastic_queue = QtWidgets.QPushButton(self.widget_2)
        self.compute_stochastic_queue.setObjectName("compute_stochastic_queue")
        self.horizontalLayout_25.addWidget(self.compute_stochastic_queue)
        self.gridLayout_5.addLayout(self.horizontalLayout_25, 2, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.comboBox_7 = QtWidgets.QComboBox(self.widget_2)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_7, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_10 = QtWidgets.QLabel(self.widget_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.mean_arrival_rate = QtWidgets.QLineEdit(self.widget_2)
        self.mean_arrival_rate.setObjectName("mean_arrival_rate")
        self.verticalLayout_6.addWidget(self.mean_arrival_rate)
        self.mean_service_rate = QtWidgets.QLineEdit(self.widget_2)
        self.mean_service_rate.setObjectName("mean_service_rate")
        self.verticalLayout_6.addWidget(self.mean_service_rate)
        self.system_capacity = QtWidgets.QLineEdit(self.widget_2)
        self.system_capacity.setObjectName("system_capacity")
        self.verticalLayout_6.addWidget(self.system_capacity)
        self.no_of_servers = QtWidgets.QLineEdit(self.widget_2)
        self.no_of_servers.setObjectName("no_of_servers")
        self.verticalLayout_6.addWidget(self.no_of_servers)
        self.gridLayout_5.addLayout(self.verticalLayout_6, 1, 1, 1, 1)
        self.determenstic_queue.addTab(self.widget_2, "")
        self.verticalLayout.addWidget(self.determenstic_queue)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 608, 21))
        self.menubar.setObjectName("menubar")
        self.menuTab1 = QtWidgets.QMenu(self.menubar)
        self.menuTab1.setObjectName("menuTab1")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuTab1.menuAction())

        self.retranslateUi(MainWindow)
        self.determenstic_queue.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox.setItemText(0, _translate("MainWindow", "D/D/1/K"))
        self.label.setText(_translate("MainWindow", "limit "))
        self.initial_no_of_customers.setText(_translate("MainWindow", "Initial number of customers"))
        self.service_rate.setText(_translate("MainWindow", "Service rate"))
        self.arrival_rate.setText(_translate("MainWindow", "Arrival rate"))
        self.la.setText(_translate("MainWindow", "Capcity"))
        self.cancel.setText(_translate("MainWindow", "Cancel"))
        self.compute_deterministic.setText(_translate("MainWindow", "Compute"))
        self.make_graph.setText(_translate("MainWindow", "Graph"))
        self.input_service_rate.setPlaceholderText(_translate("MainWindow", "u"))
        self.input_capcity.setPlaceholderText(_translate("MainWindow", "k"))
        self.input_limit.setPlaceholderText(_translate("MainWindow", "t"))
        self.input_intial_no_of_customers.setPlaceholderText(_translate("MainWindow", "M"))
        self.input_arrival_rate.setPlaceholderText(_translate("MainWindow", "lambda"))
        self.label_16.setText(_translate("MainWindow", "No of Customers "))
        self.label_14.setText(_translate("MainWindow", "Waiting Time"))
        self.no_of_customers.setText(_translate("MainWindow", "0"))
        self.waiting_time.setText(_translate("MainWindow", "0"))
        self.determenstic_queue.setTabText(self.determenstic_queue.indexOf(self.widget), _translate("MainWindow", "Determenstic Queue"))
        self.av_no_of_customers_in_q.setText(_translate("MainWindow", "0"))
        self.av_no_of_customers_in_system.setText(_translate("MainWindow", "0"))
        self.av_waiting_time_in_q.setText(_translate("MainWindow", "0"))
        self.av_waiting_time_in_system.setText(_translate("MainWindow", "0"))
        self.cancel_sto.setText(_translate("MainWindow", "Cancel"))
        self.compute_stochastic_queue.setText(_translate("MainWindow", "Compute"))
        self.label_3.setText(_translate("MainWindow", "No of Customers in Q"))
        self.label_4.setText(_translate("MainWindow", "No of Customers in System"))
        self.label_2.setText(_translate("MainWindow", "Waiting Time in Q"))
        self.label_5.setText(_translate("MainWindow", "Waiting Time in System"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "MM1"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "MM1k"))
        self.comboBox_7.setItemText(2, _translate("MainWindow", "MMc"))
        self.comboBox_7.setItemText(3, _translate("MainWindow", "MMck"))
        self.label_10.setText(_translate("MainWindow", "System Capacity"))
        self.label_9.setText(_translate("MainWindow", "Mean Arrival Rate"))
        self.label_7.setText(_translate("MainWindow", "No of Servers"))
        self.label_8.setText(_translate("MainWindow", "Mean Service Rate"))
        self.mean_arrival_rate.setPlaceholderText(_translate("MainWindow", "lambda"))
        self.mean_service_rate.setPlaceholderText(_translate("MainWindow", "u"))
        self.system_capacity.setPlaceholderText(_translate("MainWindow", "k"))
        self.no_of_servers.setPlaceholderText(_translate("MainWindow", "c"))
        self.determenstic_queue.setTabText(self.determenstic_queue.indexOf(self.widget_2), _translate("MainWindow", "Stochastic Queue"))
        self.menuTab1.setTitle(_translate("MainWindow", "File"))